### ISSUE TITLE
disable the opening of the page

### ISSUE THREAD

**Issue by adri1s** [NiceOpenSource/posttolemmy#1]
* disable the opening of the page after pushing a link
* Give the info in the pop up when the push is over

**Comment by gummyWalrus** [comment]
Issue résolue par le commit [07762](https://github.com/NiceOpenSource/posttolemmy/commit/07762c59687badd1a29760ec077bebbf11f859ce#diff-a6691e62635cd8973bdf6f031ea531572f116ae7b20c80c0ff9a68950fda09ca)
1. L'utilisateur pousse un lien
2. Le bouton affiche un état de chargement
3.  Un texte s'affiche sous le bouton pour informer l'utilisateur que le post est réussi
4. Un bouton a coté de ce texte permet d'ouvrir la page du post
