### ISSUE TITLE
reverse community name and title

### ISSUE THREAD

**Issue by adri1s** [NiceOpenSource/posttolemmy#2]
reverse community name and title in dropdown

**Comment by gummyWalrus** [comment]
issue résolue par le commit [07762](https://github.com/NiceOpenSource/posttolemmy/commit/07762c59687badd1a29760ec077bebbf11f859ce#diff-a6691e62635cd8973bdf6f031ea531572f116ae7b20c80c0ff9a68950fda09ca)
