### ISSUE TITLE
Doc install env dev

### ISSUE THREAD

**Issue by adri1s** [NiceOpenSource/posttolemmy#3]
Create a documentation on the wiki for the installation of the extension in dev mode (git clone ...)

**Comment by gummyWalrus** [comment]
Wiki rédigé : [ici](https://github.com/NiceOpenSource/posttolemmy/wiki/Install-in-development-on-Mozilla-Firefox)

**Comment by gummyWalrus** [comment]
Installation doc is complete. see [Wiki/Rolling release installation](https://github.com/NiceOpenSource/posttolemmy/wiki/Rolling-release-installation)
