### ISSUE TITLE
Use fontawesome CDN

### ISSUE THREAD

**Issue by qdequippe** [NiceOpenSource/posttolemmy#4]
👋,

Why not using directly fontawesome CDN?

**Comment by gummyWalrus** [comment]
Hello there, first issue :wave:  !
Thanks for asking, using CDNs and foreign resources is prohibited when developing browser addons.
Firefox and Chrome will block any request trying to fetch a distant code file.

See section ``Development practices`` in the [Firefox Add-on Policies](https://extensionworkshop.com/documentation/publish/add-on-policies/)

**Comment by qdequippe** [comment]
hi @gummyWalrus , good to know that :)
