### ISSUE TITLE
CI - CD for build package and release

### ISSUE THREAD

**Issue by adri1s** [NiceOpenSource/posttolemmy#9]
To make pipline of build so that to the tag we create the packages firefox and chrome and that we create a release with the packages

**Comment by gummyWalrus** [comment]
CI/CD pushed in commit [6f8581](https://github.com/NiceOpenSource/posttolemmy/commit/6f85815f9dad7ec57da6c7deeca078029578a403)

When a new tag is created extension code is packaged and signed into a firefox and a chrome extension then a release is created based on the tag name.
